"""
htmx 4.0.0 vocabulary. GENERATED by tools/gen_vocab.py from the htmx source tree;
do not edit by hand. Regenerate against a new htmx release.
"""

VERSION = '4.0.0'

# docs/reference/01-attributes/*.md
CORE_ATTRIBUTES = ['hx-get', 'hx-post', 'hx-put', 'hx-patch', 'hx-delete', 'hx-query', 'hx-trigger', 'hx-swap', 'hx-target', 'hx-select', 'hx-on', 'hx-vals', 'hx-include', 'hx-swap-oob', 'hx-select-oob', 'hx-push-url', 'hx-replace-url', 'hx-headers', 'hx-encoding', 'hx-indicator', 'hx-boost', 'hx-sync', 'hx-confirm', 'hx-validate', 'hx-disable', 'hx-ignore', 'hx-preserve', 'hx-preload', 'hx-pending', 'hx-status', 'hx-action', 'hx-method', 'hx-config', 'hx-history-elt', 'hx-morph-skip', 'hx-morph-skip-children']

# docs/extensions/*.md, the attributes each extension adds
EXTENSION_ATTRIBUTES = {'hx-multipart': ['hx-multipart', 'hx-multipart:close', 'hx-multipart:connect'], 'hx-sse': ['hx-sse', 'hx-sse:close', 'hx-sse:connect'], 'hx-ws': ['hx-ws', 'hx-ws-connect', 'hx-ws-send', 'hx-ws:connect', 'hx-ws:send'], 'hx-head': ['hx-head'], 'hx-live': ['hx-live', 'hx-live:attr', 'hx-live:hidden'], 'hx-targets': ['hx-targets', 'hx-targets:inherited'], 'hx-ptag': ['hx-ptag'], 'hx-browser-indicator': ['hx-browser-indicator'], 'hx-history-cache': ['hx-history-cache'], 'hx-csp': ['hx-csp'], 'hx-prompt': ['hx-prompt']}

# Attribute families: any name starting with one of these is valid syntax.
FAMILIES = ("hx-on", "hx-status:", "hx-live", "hx-sse", "hx-ws", "hx-multipart")

# Attributes that may sit on an ancestor and reach descendants with :inherited.
INHERITABLE = ("hx-target", "hx-swap", "hx-confirm", "hx-boost", "hx-sync", "hx-indicator",
               "hx-include", "hx-push-url", "hx-replace-url", "hx-headers", "hx-vals",
               "hx-disable", "hx-select", "hx-select-oob", "hx-encoding", "hx-validate",
               "hx-config", "hx-preload", "hx-pending", "hx-prompt", "hx-targets")

REQUEST_ATTRIBUTES = ("hx-get", "hx-post", "hx-put", "hx-patch", "hx-delete", "hx-query", "hx-action")

# docs/skills/htmx-upgrade-from-htmx2.md: htmx 2 names and what replaced them
REMOVED_ATTRIBUTES = {'hx-vars': "hx-vals='js:...'` (wrap value in `js:` prefix)", 'hx-params': 'Remove; use `htmx:config:request` event to filter params', 'hx-ext': 'Remove (just including the extension script is enough)', 'hx-disinherit': 'Remove (inheritance is explicit by default)', 'hx-inherit': 'Remove (use `:inherited` modifier on individual attributes)', 'hx-request': "hx-config='...'`. Takes HCON, which accepts the old JSON", 'hx-history': 'Remove (history no longer uses localStorage)', 'hx-disabled-elt': 'hx-disable'}

# docs/skills/htmx-guidance.md swap table, plus the aliases in src/htmx.js
SWAP_STYLES = ['innerHTML', 'outerHTML', 'textContent', 'beforebegin', 'afterbegin', 'beforeend', 'afterend', 'innerMorph', 'outerMorph', 'outerSync', 'delete', 'none']
SWAP_ALIASES = {'before': 'beforebegin', 'after': 'afterend', 'prepend': 'afterbegin', 'append': 'beforeend'}
EXTENSION_SWAP_STYLES = {'upsert': 'hx-upsert', 'download': 'hx-download'}

# docs/reference/01-attributes/08-hx-swap.md, confirmed against src/htmx.js
SWAP_MODIFIERS = ['focusScroll', 'ignoreTitle', 'scroll', 'scrollTarget', 'settle', 'show', 'showTarget', 'strip', 'swap', 'swapEmpty', 'target', 'transition']

# docs/skills/htmx-guidance.md trigger table, confirmed against src/htmx.js
TRIGGER_MODIFIERS = ['capture', 'changed', 'consume', 'delay', 'from', 'halt', 'once', 'passive', 'prevent', 'root', 'rootMargin', 'stop', 'target', 'threshold', 'throttle']
SPECIAL_TRIGGERS = ("load", "every", "intersect", "revealed")

# docs/whats-new-in-htmx-4.md: htmx 2 camelCase event names and their htmx 4 form
HTMX2_EVENT_NAMES = {'htmx:afterOnLoad': 'htmx:after:init', 'htmx:afterProcessNode': 'htmx:after:init', 'htmx:afterRequest': 'htmx:after:request', 'htmx:afterSettle': 'htmx:after:settle', 'htmx:afterSwap': 'htmx:after:swap', 'htmx:beforeCleanupElement': 'htmx:before:cleanup', 'htmx:beforeHistorySave': 'htmx:before:history:update', 'htmx:beforeOnLoad': 'htmx:before:init', 'htmx:beforeProcessNode': 'htmx:before:process', 'htmx:beforeRequest': 'htmx:before:request', 'htmx:beforeSwap': 'htmx:before:swap', 'htmx:configRequest': 'htmx:config:request', 'htmx:historyCacheMiss': 'htmx:before:history:restore', 'htmx:historyRestore': 'htmx:before:history:restore', 'htmx:oobAfterSwap': 'htmx:after:swap', 'htmx:oobBeforeSwap': 'htmx:before:swap', 'htmx:pushedIntoHistory': 'htmx:after:history:push', 'htmx:replacedInHistory': 'htmx:after:history:replace', 'htmx:responseError': 'htmx:response:error', 'htmx:sendError': 'htmx:error', 'htmx:swapError': 'htmx:error', 'htmx:targetError': 'htmx:error', 'htmx:load': '(see htmx-2-compat.js)', 'htmx:beforeHistoryUpdate': '(see htmx-2-compat.js)', 'htmx:beforeSend': '(see htmx-2-compat.js)', 'htmx:beforeTransition': '(see htmx-2-compat.js)'}
